### ISSUE TITLE
Show also the player who has drawn the image in the final screen

### ISSUE THREAD

**Issue by Agreon** [Kkoile/skess#4]
I can help with that ;)

**Comment by Kkoile** [comment]
Yeah, the final screen is unfortunately the screen where I didn't think so much about design and usability. I guess there is a lot which can be done on this page :-)
Feel free to share a design idea, or even implement it. 

A small disclaimer: Skess is my first react.js project, so the code might not be so well structured and it could be that it doesn't follow best practices. So don't be shocked if you try to contribute ;-)

**Comment by Agreon** [comment]
The code was okay ;)
Actually pretty neat for your first project.

I've created a PR.

**Comment by Kkoile** [comment]
fixed by #5
